import { cents } from "@/lib/money";
import { isPreorderRadarEligible } from "@/lib/sealedTypes";
import type { ProductSeed } from "@/lib/retailers/types";

/**
 * Catalog tuned for ~July 2026.
 * Prices come from TCGPlayer (via tcgcsv) using tcgplayerProductId + groupId.
 * msrpCents is official Wizards MSRP for deal scoring — not street price.
 */
export const SEALED_CATALOG: ProductSeed[] = [
  // —— Just released / still hot ——
  {
    id: "msh-play-booster-box",
    name: "Marvel Super Heroes Play Booster Box",
    setName: "Marvel Super Heroes",
    category: "box",
    sealedType: "play_booster_box",
    releaseDate: "2026-06-26",
    msrpCents: cents(143.76),
    tcgplayerGroupId: 24553,
    tcgplayerProductId: 675603,
  },
  {
    id: "msh-collector-booster-display",
    name: "Marvel Super Heroes Collector Booster Display",
    setName: "Marvel Super Heroes",
    category: "box",
    sealedType: "collector_booster_display",
    releaseDate: "2026-06-26",
    msrpCents: cents(299.88),
    tcgplayerGroupId: 24553,
    tcgplayerProductId: 675606,
  },
  {
    id: "msh-bundle",
    name: "Marvel Super Heroes Bundle",
    setName: "Marvel Super Heroes",
    category: "bundle",
    sealedType: "bundle",
    releaseDate: "2026-06-26",
    msrpCents: cents(49.99),
    tcgplayerGroupId: 24553,
    tcgplayerProductId: 675615,
  },

  // —— Upcoming (preorder) ——
  {
    id: "hobbit-play-booster-box",
    name: "The Hobbit Play Booster Box",
    setName: "The Hobbit",
    category: "box",
    sealedType: "play_booster_box",
    releaseDate: "2026-08-14",
    msrpCents: cents(143.76),
    tcgplayerGroupId: 24683,
    tcgplayerProductId: 692960,
  },
  {
    id: "hobbit-collector-booster-display",
    name: "The Hobbit Collector Booster Display",
    setName: "The Hobbit",
    category: "box",
    sealedType: "collector_booster_display",
    releaseDate: "2026-08-14",
    msrpCents: cents(299.88),
    tcgplayerGroupId: 24683,
    tcgplayerProductId: 692963,
  },
  {
    id: "hobbit-bundle",
    name: "The Hobbit Bundle",
    setName: "The Hobbit",
    category: "bundle",
    sealedType: "bundle",
    releaseDate: "2026-08-14",
    msrpCents: cents(49.99),
    tcgplayerGroupId: 24683,
    tcgplayerProductId: 692966,
  },
  {
    id: "reality-fracture-play-booster-box",
    name: "Reality Fracture Play Booster Box",
    setName: "Reality Fracture",
    category: "box",
    sealedType: "play_booster_box",
    releaseDate: "2026-10-02",
    msrpCents: cents(143.76),
    tcgplayerGroupId: 24684,
    tcgplayerProductId: 692980,
  },
  {
    id: "reality-fracture-collector-booster-display",
    name: "Reality Fracture Collector Booster Display",
    setName: "Reality Fracture",
    category: "box",
    sealedType: "collector_booster_display",
    releaseDate: "2026-10-02",
    msrpCents: cents(299.88),
    tcgplayerGroupId: 24684,
    tcgplayerProductId: 692983,
  },
  {
    id: "star-trek-play-booster-box",
    name: "Star Trek Play Booster Box",
    setName: "Star Trek",
    category: "box",
    sealedType: "play_booster_box",
    releaseDate: "2026-11-13",
    msrpCents: cents(143.76),
    tcgplayerGroupId: 24766,
    tcgplayerProductId: 706138,
  },
  {
    id: "star-trek-collector-booster-display",
    name: "Star Trek Collector Booster Display",
    setName: "Star Trek",
    category: "box",
    sealedType: "collector_booster_display",
    releaseDate: "2026-11-13",
    msrpCents: cents(299.88),
    tcgplayerGroupId: 24766,
    tcgplayerProductId: 706142,
  },

  // —— Released catalog for budget deals ——
  {
    id: "strixhaven-secrets-play-booster-box",
    name: "Secrets of Strixhaven Play Booster Box",
    setName: "Secrets of Strixhaven",
    category: "box",
    sealedType: "play_booster_box",
    releaseDate: "2026-04-24",
    msrpCents: cents(143.76),
    tcgplayerGroupId: 24601,
    tcgplayerProductId: 675555,
  },
  {
    id: "strixhaven-secrets-collector-booster-display",
    name: "Secrets of Strixhaven Collector Booster Display",
    setName: "Secrets of Strixhaven",
    category: "box",
    sealedType: "collector_booster_display",
    releaseDate: "2026-04-24",
    msrpCents: cents(299.88),
    tcgplayerGroupId: 24601,
    tcgplayerProductId: 675558,
  },
  {
    id: "tmnt-play-booster-box",
    name: "Teenage Mutant Ninja Turtles Play Booster Box",
    setName: "Teenage Mutant Ninja Turtles",
    category: "box",
    sealedType: "play_booster_box",
    releaseDate: "2026-03-06",
    msrpCents: cents(143.76),
    tcgplayerGroupId: 24495,
    tcgplayerProductId: 657849,
  },
  {
    id: "tmnt-collector-booster-display",
    name: "Teenage Mutant Ninja Turtles Collector Booster Display",
    setName: "Teenage Mutant Ninja Turtles",
    category: "box",
    sealedType: "collector_booster_display",
    releaseDate: "2026-03-06",
    msrpCents: cents(299.88),
    tcgplayerGroupId: 24495,
    tcgplayerProductId: 657852,
  },
  {
    id: "lorwyn-eclipsed-play-booster-box",
    name: "Lorwyn Eclipsed Play Booster Box",
    setName: "Lorwyn Eclipsed",
    category: "box",
    sealedType: "play_booster_box",
    releaseDate: "2026-01-23",
    msrpCents: cents(143.76),
    tcgplayerGroupId: 24463,
    tcgplayerProductId: 656312,
  },
  {
    id: "lorwyn-eclipsed-collector-booster-display",
    name: "Lorwyn Eclipsed Collector Booster Display",
    setName: "Lorwyn Eclipsed",
    category: "box",
    sealedType: "collector_booster_display",
    releaseDate: "2026-01-23",
    msrpCents: cents(299.88),
    tcgplayerGroupId: 24463,
    tcgplayerProductId: 656322,
  },
  {
    id: "fdn-play-booster-box",
    name: "Foundations Play Booster Box",
    setName: "Foundations",
    category: "box",
    sealedType: "play_booster_box",
    releaseDate: "2024-11-15",
    msrpCents: cents(143.76),
    tcgplayerGroupId: 23556,
    tcgplayerProductId: 562118,
  },
  {
    id: "fdn-collector-booster-display",
    name: "Foundations Collector Booster Display",
    setName: "Foundations",
    category: "box",
    sealedType: "collector_booster_display",
    releaseDate: "2024-11-15",
    msrpCents: cents(299.88),
    tcgplayerGroupId: 23556,
    tcgplayerProductId: 562122,
  },
  {
    id: "fdn-bundle",
    name: "Foundations Bundle",
    setName: "Foundations",
    category: "bundle",
    sealedType: "bundle",
    releaseDate: "2024-11-15",
    msrpCents: cents(44.99),
    tcgplayerGroupId: 23556,
    tcgplayerProductId: 562125,
  },
  {
    id: "mh3-play-booster-box",
    name: "Modern Horizons 3 Play Booster Box",
    setName: "Modern Horizons 3",
    category: "box",
    sealedType: "play_booster_box",
    releaseDate: "2024-06-14",
    msrpCents: cents(159.99),
    tcgplayerGroupId: 23444,
    tcgplayerProductId: 541164,
  },
  {
    id: "mh3-collector-booster-display",
    name: "Modern Horizons 3 Collector Booster Display",
    setName: "Modern Horizons 3",
    category: "box",
    sealedType: "collector_booster_display",
    releaseDate: "2024-06-14",
    msrpCents: cents(299.99),
    tcgplayerGroupId: 23444,
    tcgplayerProductId: 541179,
  },
  {
    id: "blb-commander-deck-display",
    name: "Bloomburrow Commander Deck Display",
    setName: "Bloomburrow",
    category: "commander",
    sealedType: "commander_deck_display",
    releaseDate: "2024-08-02",
    msrpCents: cents(179.96),
    tcgplayerGroupId: 23448,
    tcgplayerProductId: 541250,
  },
  {
    id: "dsk-play-booster-box",
    name: "Duskmourn Play Booster Box",
    setName: "Duskmourn: House of Horror",
    category: "box",
    sealedType: "play_booster_box",
    releaseDate: "2024-09-27",
    msrpCents: cents(143.76),
    tcgplayerGroupId: 23550,
    tcgplayerProductId: 557241,
  },
  {
    id: "dsk-collector-booster-display",
    name: "Duskmourn Collector Booster Display",
    setName: "Duskmourn: House of Horror",
    category: "box",
    sealedType: "collector_booster_display",
    releaseDate: "2024-09-27",
    msrpCents: cents(299.88),
    tcgplayerGroupId: 23550,
    tcgplayerProductId: 557244,
  },
];

export function productSearchText(p: ProductSeed): string {
  return `${p.name} ${p.setName} ${p.category} ${p.sealedType} sealed`.toLowerCase();
}

export function preorderCatalog(now = new Date()): ProductSeed[] {
  return SEALED_CATALOG.filter((p) => isPreorderRadarEligible(p.releaseDate, now));
}

export function catalogById(id: string): ProductSeed | undefined {
  return SEALED_CATALOG.find((p) => p.id === id);
}
