import { cents } from "@/lib/money";
import { isPreorderRadarEligible, isUpcomingSet } from "@/lib/sealedTypes";
import type { ProductSeed } from "@/lib/retailers/types";

/**
 * Catalog tuned for ~July 2026.
 * Street prices come from TCGPlayer / retailer pages.
 * msrpCents is official Wizards MSRP (pack MSRP × packs in display) for deal scoring.
 *
 * 2026 standard sets: Play $5.49 × 30 = $164.70 · Collector $26.99 × 12 = $323.88 · Bundle $57.99
 * 2026 UB premium (Marvel / Hobbit / Star Trek / TMNT):
 *   Play $6.99 × 30 = $209.70 · Collector $37.99 × 12 = $455.88 · Bundle $69.99
 */
export const SEALED_CATALOG: ProductSeed[] = [
  // —— Just released / still hot ——
  {
    id: "msh-play-booster-box",
    name: "Marvel Super Heroes Play Booster Box",
    setName: "Marvel Super Heroes",
    category: "box",
    sealedType: "play_booster_box",
    releaseDate: "2026-06-26",
    msrpCents: cents(209.7),
    packCount: 30,
    tcgplayerGroupId: 24553,
    tcgplayerProductId: 675603,
    listingUrls: {
      card_kingdom:
        "https://www.cardkingdom.com/mtg-sealed/marvel-super-heroes-play-booster-box",
      starcitygames:
        "https://starcitygames.com/marvel-super-heroes-play-booster-box-sld-mtg-bbx-mshplay-en/",
    },
  },
  {
    id: "msh-collector-booster-display",
    name: "Marvel Super Heroes Collector Booster Display",
    setName: "Marvel Super Heroes",
    category: "box",
    sealedType: "collector_booster_display",
    releaseDate: "2026-06-26",
    msrpCents: cents(455.88),
    packCount: 12,
    tcgplayerGroupId: 24553,
    tcgplayerProductId: 675606,
  },
  {
    id: "msh-bundle",
    name: "Marvel Super Heroes Bundle",
    setName: "Marvel Super Heroes",
    category: "bundle",
    sealedType: "bundle",
    releaseDate: "2026-06-26",
    msrpCents: cents(69.99),
    packCount: 9,
    tcgplayerGroupId: 24553,
    tcgplayerProductId: 675615,
  },
  {
    id: "msh-gift-bundle",
    name: "Marvel Super Heroes Gift Bundle",
    setName: "Marvel Super Heroes",
    category: "bundle",
    sealedType: "gift_bundle",
    releaseDate: "2026-06-26",
    msrpCents: cents(89.99),
    packCount: 10, // 9 play + 1 collector
    tcgplayerGroupId: 24553,
    tcgplayerProductId: 675617,
  },
  {
    id: "msh-collector-booster-omega",
    name: "Marvel Super Heroes Collector Booster Omega",
    setName: "Marvel Super Heroes",
    category: "booster",
    sealedType: "collector_booster_omega",
    releaseDate: "2026-06-26",
    msrpCents: cents(44.99),
    packCount: 1,
    tcgplayerGroupId: 24553,
    tcgplayerProductId: 703190,
  },
  {
    id: "msh-scene-box-heroes-united",
    name: "Marvel Super Heroes Scene Box - Heroes United",
    setName: "Marvel Super Heroes",
    category: "other",
    sealedType: "scene_box",
    releaseDate: "2026-06-26",
    msrpCents: cents(41.99),
    packCount: 3,
    tcgplayerGroupId: 24553,
    tcgplayerProductId: 675619,
  },

  // —— Upcoming (preorder) ——
  {
    id: "hobbit-play-booster-box",
    name: "The Hobbit Play Booster Box",
    setName: "The Hobbit",
    category: "box",
    sealedType: "play_booster_box",
    releaseDate: "2026-08-14",
    msrpCents: cents(209.7),
    packCount: 30,
    tcgplayerGroupId: 24683,
    tcgplayerProductId: 692960,
    listingUrls: {
      starcitygames:
        "https://starcitygames.com/the-hobbit-play-booster-box-sld-mtg-bbx-hobplay-en/",
      miniature_market:
        "https://www.miniaturemarket.com/MTG-The-Hobbit-Play-Booster-Box-30-Preorder/WOCD5658-BOX",
      card_kingdom:
        "https://www.cardkingdom.com/mtg-sealed/the-hobbit-play-booster-box",
      flipside_gaming:
        "https://flipsidegaming.com/products/mtg-the-hobbit-play-booster-box",
      forge_and_fire:
        "https://forgeandfiregaming.com/magic-the-gathering/the-hobbit-play-booster-display/",
      amazon: "https://www.amazon.com/dp/B0GXCBJG9L",
    },
  },
  {
    id: "hobbit-collector-booster-display",
    name: "The Hobbit Collector Booster Display",
    setName: "The Hobbit",
    category: "box",
    sealedType: "collector_booster_display",
    releaseDate: "2026-08-14",
    msrpCents: cents(455.88),
    packCount: 12,
    tcgplayerGroupId: 24683,
    tcgplayerProductId: 692963,
    listingUrls: {
      flipside_gaming:
        "https://flipsidegaming.com/products/mtg-the-hobbit-collector-booster-box",
      forge_and_fire:
        "https://forgeandfiregaming.com/magic-the-gathering/the-hobbit-collector-booster-booster-display/",
    },
  },
  {
    id: "hobbit-bundle",
    name: "The Hobbit Bundle",
    setName: "The Hobbit",
    category: "bundle",
    sealedType: "bundle",
    releaseDate: "2026-08-14",
    msrpCents: cents(69.99),
    packCount: 9,
    tcgplayerGroupId: 24683,
    tcgplayerProductId: 692966,
    listingUrls: {
      miniature_market:
        "https://www.miniaturemarket.com/MTG-The-Hobbit-Bundle-Preorder/WOCD5664",
    },
  },
  {
    id: "hobbit-gift-bundle",
    name: "The Hobbit Gift Bundle",
    setName: "The Hobbit",
    category: "bundle",
    sealedType: "gift_bundle",
    releaseDate: "2026-09-04",
    msrpCents: cents(89.99),
    packCount: 10,
    tcgplayerGroupId: 24683,
    tcgplayerProductId: 692971,
    listingUrls: {
      miniature_market:
        "https://www.miniaturemarket.com/MTG-The-Hobbit-Gift-Bundle-Preorder/WOCD5663",
    },
  },
  {
    id: "hobbit-scene-box-crack-the-plates",
    name: "The Hobbit Scene Box - Crack the Plates",
    setName: "The Hobbit",
    category: "other",
    sealedType: "scene_box",
    releaseDate: "2026-08-14",
    msrpCents: cents(41.99),
    packCount: 3,
    tcgplayerGroupId: 24683,
    tcgplayerProductId: 692968,
  },
  {
    id: "reality-fracture-play-booster-box",
    name: "Reality Fracture Play Booster Box",
    setName: "Reality Fracture",
    category: "box",
    sealedType: "play_booster_box",
    releaseDate: "2026-10-02",
    msrpCents: cents(164.7),
    packCount: 30,
    tcgplayerGroupId: 24684,
    tcgplayerProductId: 692980,
  },
  {
    id: "reality-fracture-collector-booster-display",
    name: "Reality Fracture Collector Booster Display",
    setName: "Reality Fracture",
    category: "box",
    sealedType: "collector_booster_display",
    releaseDate: "2026-10-02",
    msrpCents: cents(323.88),
    packCount: 12,
    tcgplayerGroupId: 24684,
    tcgplayerProductId: 692983,
  },
  {
    id: "star-trek-play-booster-box",
    name: "Star Trek Play Booster Box",
    setName: "Star Trek",
    category: "box",
    sealedType: "play_booster_box",
    releaseDate: "2026-11-20",
    msrpCents: cents(209.7),
    packCount: 30,
    tcgplayerGroupId: 24766,
    tcgplayerProductId: 706138,
  },
  {
    id: "star-trek-collector-booster-display",
    name: "Star Trek Collector Booster Display",
    setName: "Star Trek",
    category: "box",
    sealedType: "collector_booster_display",
    releaseDate: "2026-11-20",
    msrpCents: cents(455.88),
    packCount: 12,
    tcgplayerGroupId: 24766,
    tcgplayerProductId: 706142,
  },
  {
    id: "star-trek-bundle",
    name: "Star Trek Bundle",
    setName: "Star Trek",
    category: "bundle",
    sealedType: "bundle",
    releaseDate: "2026-11-20",
    msrpCents: cents(69.99),
    packCount: 9,
    tcgplayerGroupId: 24766,
    tcgplayerProductId: 706150,
  },
  {
    id: "star-trek-beam-me-up-bundle",
    name: "Star Trek Beam Me Up Bundle",
    setName: "Star Trek",
    category: "bundle",
    sealedType: "specialty_bundle",
    releaseDate: "2026-11-20",
    msrpCents: cents(99.99),
    packCount: 9, // 8 play + 1 collector
    tcgplayerGroupId: 24766,
    tcgplayerProductId: 706154,
  },
  {
    id: "star-trek-scene-box-enterprise-q",
    name: "Star Trek Scene Box - Enterprise-Q",
    setName: "Star Trek",
    category: "other",
    sealedType: "scene_box",
    releaseDate: "2026-11-20",
    msrpCents: cents(41.99),
    packCount: 3,
    tcgplayerGroupId: 24766,
    tcgplayerProductId: 706157,
  },

  // —— Released catalog for budget deals ——
  {
    id: "strixhaven-secrets-play-booster-box",
    name: "Secrets of Strixhaven Play Booster Box",
    setName: "Secrets of Strixhaven",
    category: "box",
    sealedType: "play_booster_box",
    releaseDate: "2026-04-24",
    msrpCents: cents(164.7),
    packCount: 30,
    tcgplayerGroupId: 24601,
    tcgplayerProductId: 675555,
  },
  {
    id: "strixhaven-secrets-collector-booster-display",
    name: "Secrets of Strixhaven Collector Booster Display",
    setName: "Secrets of Strixhaven",
    category: "box",
    sealedType: "collector_booster_display",
    releaseDate: "2026-04-24",
    msrpCents: cents(323.88),
    packCount: 12,
    tcgplayerGroupId: 24601,
    tcgplayerProductId: 675558,
  },
  {
    id: "strixhaven-secrets-bundle",
    name: "Secrets of Strixhaven Bundle",
    setName: "Secrets of Strixhaven",
    category: "bundle",
    sealedType: "bundle",
    releaseDate: "2026-04-24",
    msrpCents: cents(57.99),
    packCount: 9,
    tcgplayerGroupId: 24601,
    tcgplayerProductId: 675561,
  },
  {
    id: "strixhaven-secrets-codex-bundle",
    name: "Secrets of Strixhaven Codex Bundle",
    setName: "Secrets of Strixhaven",
    category: "bundle",
    sealedType: "specialty_bundle",
    releaseDate: "2026-04-24",
    msrpCents: cents(89.99),
    packCount: 8, // 6 play + 2 collector
    tcgplayerGroupId: 24601,
    tcgplayerProductId: 675563,
  },
  {
    id: "strixhaven-secrets-collector-booster-omega",
    name: "Secrets of Strixhaven Collector Booster Omega",
    setName: "Secrets of Strixhaven",
    category: "booster",
    sealedType: "collector_booster_omega",
    releaseDate: "2026-04-24",
    msrpCents: cents(44.99),
    packCount: 1,
    tcgplayerGroupId: 24601,
    tcgplayerProductId: 691629,
  },
  {
    id: "tmnt-play-booster-box",
    name: "Teenage Mutant Ninja Turtles Play Booster Box",
    setName: "Teenage Mutant Ninja Turtles",
    category: "box",
    sealedType: "play_booster_box",
    releaseDate: "2026-03-06",
    msrpCents: cents(209.7),
    packCount: 30,
    tcgplayerGroupId: 24495,
    tcgplayerProductId: 657849,
  },
  {
    id: "tmnt-collector-booster-display",
    name: "Teenage Mutant Ninja Turtles Collector Booster Display",
    setName: "Teenage Mutant Ninja Turtles",
    category: "box",
    sealedType: "collector_booster_display",
    releaseDate: "2026-03-06",
    msrpCents: cents(455.88),
    packCount: 12,
    tcgplayerGroupId: 24495,
    tcgplayerProductId: 657852,
  },
  {
    id: "tmnt-bundle",
    name: "Teenage Mutant Ninja Turtles Bundle",
    setName: "Teenage Mutant Ninja Turtles",
    category: "bundle",
    sealedType: "bundle",
    releaseDate: "2026-03-06",
    msrpCents: cents(69.99),
    packCount: 9,
    tcgplayerGroupId: 24495,
    tcgplayerProductId: 657856,
  },
  {
    id: "tmnt-pizza-bundle",
    name: "Teenage Mutant Ninja Turtles Pizza Bundle",
    setName: "Teenage Mutant Ninja Turtles",
    category: "bundle",
    sealedType: "specialty_bundle",
    releaseDate: "2026-03-06",
    msrpCents: cents(99.99),
    packCount: 9,
    tcgplayerGroupId: 24495,
    tcgplayerProductId: 657863,
  },
  {
    id: "tmnt-collector-booster-omega",
    name: "Teenage Mutant Ninja Turtles Collector Booster Omega",
    setName: "Teenage Mutant Ninja Turtles",
    category: "booster",
    sealedType: "collector_booster_omega",
    releaseDate: "2026-03-06",
    msrpCents: cents(44.99),
    packCount: 1,
    tcgplayerGroupId: 24495,
    tcgplayerProductId: 683152,
  },
  {
    id: "lorwyn-eclipsed-play-booster-box",
    name: "Lorwyn Eclipsed Play Booster Box",
    setName: "Lorwyn Eclipsed",
    category: "box",
    sealedType: "play_booster_box",
    releaseDate: "2026-01-23",
    msrpCents: cents(164.7),
    packCount: 30,
    tcgplayerGroupId: 24463,
    tcgplayerProductId: 656312,
  },
  {
    id: "lorwyn-eclipsed-collector-booster-display",
    name: "Lorwyn Eclipsed Collector Booster Display",
    setName: "Lorwyn Eclipsed",
    category: "box",
    sealedType: "collector_booster_display",
    releaseDate: "2026-01-23",
    msrpCents: cents(323.88),
    packCount: 12,
    tcgplayerGroupId: 24463,
    tcgplayerProductId: 656322,
  },
  {
    id: "lorwyn-eclipsed-bundle",
    name: "Lorwyn Eclipsed Bundle",
    setName: "Lorwyn Eclipsed",
    category: "bundle",
    sealedType: "bundle",
    releaseDate: "2026-01-23",
    msrpCents: cents(57.99),
    packCount: 9,
    tcgplayerGroupId: 24463,
    tcgplayerProductId: 656340,
  },
  {
    id: "lorwyn-eclipsed-collector-booster-omega",
    name: "Lorwyn Eclipsed Collector Booster Omega",
    setName: "Lorwyn Eclipsed",
    category: "booster",
    sealedType: "collector_booster_omega",
    releaseDate: "2026-01-23",
    msrpCents: cents(44.99),
    packCount: 1,
    tcgplayerGroupId: 24463,
    tcgplayerProductId: 656321,
  },
  {
    id: "fdn-play-booster-box",
    name: "Foundations Play Booster Box",
    setName: "Foundations",
    category: "box",
    sealedType: "play_booster_box",
    releaseDate: "2024-11-15",
    msrpCents: cents(143.76),
    packCount: 36,
    tcgplayerGroupId: 23556,
    tcgplayerProductId: 562118,
  },
  {
    id: "fdn-collector-booster-display",
    name: "Foundations Collector Booster Display",
    setName: "Foundations",
    category: "box",
    sealedType: "collector_booster_display",
    releaseDate: "2024-11-15",
    msrpCents: cents(299.88),
    packCount: 12,
    tcgplayerGroupId: 23556,
    tcgplayerProductId: 562122,
  },
  {
    id: "fdn-bundle",
    name: "Foundations Bundle",
    setName: "Foundations",
    category: "bundle",
    sealedType: "bundle",
    releaseDate: "2024-11-15",
    msrpCents: cents(44.99),
    packCount: 9,
    tcgplayerGroupId: 23556,
    tcgplayerProductId: 562125,
  },
  {
    id: "mh3-play-booster-box",
    name: "Modern Horizons 3 Play Booster Box",
    setName: "Modern Horizons 3",
    category: "box",
    sealedType: "play_booster_box",
    releaseDate: "2024-06-14",
    msrpCents: cents(274.99),
    packCount: 36,
    tcgplayerGroupId: 23444,
    tcgplayerProductId: 541164,
  },
  {
    id: "mh3-collector-booster-display",
    name: "Modern Horizons 3 Collector Booster Display",
    setName: "Modern Horizons 3",
    category: "box",
    sealedType: "collector_booster_display",
    releaseDate: "2024-06-14",
    msrpCents: cents(299.99),
    packCount: 12,
    tcgplayerGroupId: 23444,
    tcgplayerProductId: 541179,
  },
  {
    id: "blb-commander-deck-display",
    name: "Bloomburrow Commander Deck Display",
    setName: "Bloomburrow",
    category: "commander",
    sealedType: "commander_deck_display",
    releaseDate: "2024-08-02",
    msrpCents: cents(179.96),
    packCount: 4,
    tcgplayerGroupId: 23448,
    tcgplayerProductId: 541250,
  },
  {
    id: "dsk-play-booster-box",
    name: "Duskmourn Play Booster Box",
    setName: "Duskmourn: House of Horror",
    category: "box",
    sealedType: "play_booster_box",
    releaseDate: "2024-09-27",
    msrpCents: cents(143.76),
    packCount: 36,
    tcgplayerGroupId: 23550,
    tcgplayerProductId: 557241,
  },
  {
    id: "dsk-collector-booster-display",
    name: "Duskmourn Collector Booster Display",
    setName: "Duskmourn: House of Horror",
    category: "box",
    sealedType: "collector_booster_display",
    releaseDate: "2024-09-27",
    msrpCents: cents(299.88),
    packCount: 12,
    tcgplayerGroupId: 23550,
    tcgplayerProductId: 557244,
  },
];

export function productSearchText(p: ProductSeed): string {
  return `${p.name} ${p.setName} ${p.category} ${p.sealedType} sealed`.toLowerCase();
}

export function preorderCatalog(now = new Date()): ProductSeed[] {
  return SEALED_CATALOG.filter((p) => isPreorderRadarEligible(p.releaseDate, now));
}

/** Unique set names with a future release date (sorted). */
export function preorderSetNames(now = new Date()): string[] {
  const dates = new Map<string, string>();
  for (const p of SEALED_CATALOG) {
    if (!isUpcomingSet(p.releaseDate, now)) continue;
    const prev = dates.get(p.setName);
    if (!prev || p.releaseDate < prev) dates.set(p.setName, p.releaseDate);
  }
  return [...dates.entries()]
    .sort((a, b) => a[1].localeCompare(b[1]) || a[0].localeCompare(b[0]))
    .map(([setName]) => setName);
}

export function catalogById(id: string): ProductSeed | undefined {
  return SEALED_CATALOG.find((p) => p.id === id);
}
